### ISSUE TITLE
Support for Inbox (A)

### ISSUE THREAD

**Issue by theemstra** [muan/github-gmail#33]
So! The successor of Gmail is in the process of getting ready, this featureset is very nice and it would be a waste if it wouldn't be integrated with Inbox somehow.

If you like I can send you an invite, maybe we can work it out!

**Comment by david-gnext** [comment]
i like it

**Comment by muan** [comment]
Hi there, I've added support for Inbox **for Chrome**. I'll create a separate issue for it to be ported into Firefox. 

One thing to note though – Inbox uses `return/enter` as the key to expand a conversation, so the default trigger `ctrl + enter` for quick actions won't work; hence I made it work with the triggers defaulted to `shift + g` and `shift + b`, thy are customizable in the settings.

Let me know how it goes!
