### ISSUE TITLE
Port Inbox support from Chrome to Firefox

### ISSUE THREAD

**Issue by muan** [muan/github-gmail#36]
Changes in https://github.com/muan/github-gmail/compare/0.6.3...0.6.4 should be ported to Firefox.

**Comment by LukeeeeBennett** [comment]
I was looking to do this tonight but noticed the Inbox support wasn't working on Chrome, or at least for me. I noticed all of the 2-letter class names it is querying are non-existent in my Inbox DOM. It does however still work on Gmail as those class names are present.

From what I understand Inbox support is already implemented for Chrome so I'm wondering;
Is this just on my side, an extension I'm already using? Or, has Google updated some of the Inbox DOM class names? Alternatively, I could be acting a foo'.

**Comment by ErinCall** [comment]
Everything should be up to date as of #59; it definitely includes inbox support.

**Comment by muan** [comment]
Closing in favor of https://github.com/muan/github-gmail/issues/70
