### ISSUE TITLE
Error on Firefox

### ISSUE THREAD

**Issue by Darksmurf** [muan/github-gmail#42]
Says "This add-on could not be installed because it appears to be corrupt"

**Comment by muan** [comment]
Managed to install it on 37.0.2 just now,

![image](https://cloud.githubusercontent.com/assets/1153134/7633917/218fbd26-fa8a-11e4-90ef-c0dbabfcb86e.png)

What version are you on? Perhaps that's the reason.

**Comment by Darksmurf** [comment]
Maybe... I'm on a highly restrictive computer, because its a my school
one... I'll try it on my personal one and get back to you on that :)

**Comment by Darksmurf** [comment]
I currently have version 30.0

**Comment by muan** [comment]
30.0 is quite old now. 😨
