### ISSUE TITLE
Little bug

### ISSUE THREAD

**Issue by Angelfire** [muan/github-gmail#43]
I found a little and innocent "typo bug"

https://github.com/muan/github-gmail/blob/master/chrome/src/inject/inject.js#L151

"crtl" string

```
if(key == "crtl")  trueOrFalse.push(event.ctrlKey)
```

**Comment by muan** [comment]
haiiiiiii good find! Thank you!

**Comment by muan** [comment]
Fixed in 2cbb56c9668d89c7a6b11bfa8dc76665894f2c5f.
