### ISSUE TITLE
Don't change focus to new tabs (preference?)

### ISSUE THREAD

**Issue by johndbritton** [muan/github-gmail#46]
I like using the button to open issues on GitHub, but when I triage my notifications I like to go through them quickly and then come back to certain issues that need more attention.

Changing focus to the newly opened tab breaks my flow, I'd like for the new tabs to be opened, but not change focus to them.

If you don't want to change the default behavior, would you be open to adding a preference for this @muan?

**Comment by muan** [comment]
Haiiii I thought this looks so familiar 👉 #24, did it stop working?

**Comment by johndbritton** [comment]
:laughing: don't mind me. Thanks @muan.
