### ISSUE TITLE
"Visit Thread on GitHub" takes an different link to unsubscribe 

### ISSUE THREAD

**Issue by ikeike443** [muan/github-gmail#51]
@muan 

I've found that "Visit Thread on GitHub" takes an different link to unsubscribe instead of the link to an issue itself.

The below is the html code from the chrome dev tool(replaced the hash with a meaningless string though):
```
<a class="github-link T-I J-J5-Ji lS T-I-ax7 ar7" target="_blank" href="https://github.com/notifications/unsubscribe/xxxhogehogexxxx">Visit Thread on GitHub</a>
```

So when pushing the "Visit Thread on GitHub"  button, then you unsubscribe the thread..

**Comment by ikeike443** [comment]
ah, I didn't notice [this PR] already exists..

**Comment by muan** [comment]
This is out with [`0.7.0`](https://github.com/muan/github-gmail/releases), also added a mute button + shortcut, and uploaded to the Chrome web store!

**Comment by ikeike443** [comment]
@muan Thanks! This new version works quite well!!
