### ISSUE TITLE
Mute button is broken

### ISSUE THREAD

**Issue by muan** [muan/github-gmail#60]
:(

GitHub (well, we) changed it so that the unsubscribe link in the footer requires auth, for good reasons, and the list-unsubscribe link is still not in the DOM so again we seem to be stuck.

**Comment by sam-github** [comment]
Does it still not work?

I'm dieing for a fast way to mute threads directly from the main gmail thread index.

**Comment by muan** [comment]
> Does it still not work?
> 
> I'm dieing for a fast way to mute threads directly from the main gmail thread index.

I'm fixing the mute button, but it is in the mail view instead of the list view. I don't think there's a way to do that unfortunately.

**Comment by sam-github** [comment]
There are technical obstacles to to making the "View Issue" button actually become a "Mute Issue" button? Or to having a second button?

I wonder if I could make it happen with Greasemonkey, I've never worked with it, but it might the time.

A "Mute" in the mail view will be a bit helpful. For issues with small descriptions, the "mute" link is visible on the first email in the thread, so there is no need, but if the PR changed lots of files or has a long description, then its necessary to scroll down and look for the mute link, so having a "mute" button at the top will be helpful.

Simply moving the "mute" link in the notification email to the top of the email would help a lot, irrespective of any gmail specific integrations.

**Comment by muan** [comment]
> There are technical obstacles to to making the "View Issue" button actually become a "Mute Issue" button? Or to having a second button?

The button on the list view is coming from email headers afaik, so that'd be a feature request to GitHub. 

For this extension, it'd not be possible to add mute to the list view because the mute link is NOT rendered on the view and there is no way to "generate" it. The mute button interaction for this extension is shown in the readme: https://github.com/muan/github-gmail#mute-thread

**Comment by sam-github** [comment]
Understood, if you fix the mute, I'll use it!  Thanks.
