### ISSUE TITLE
Removal of jQuery broke options page

### ISSUE THREAD

**Issue by shouichi** [muan/github-gmail#69]
Though jQuery was removed in 24919e3c2e21259df3409ca24ecb9ea7a4aa69d0, it seems like `options.js` relies on jQuery.

https://github.com/muan/github-gmail/blob/94936c39c7057d827c354d2bffc0a3a73ee0035a/chrome/src/options/options.js#L1

Are you planning to migrate to something like `fetch`?

Thanks!

**Comment by muan** [comment]
Thank you! I completely forgot about the options page. I just published `0.8.2`. It should be public shortly.
