### ISSUE TITLE
Make it a WebExtension (for Firefox Quantum+ compatibility)

### ISSUE THREAD

**Issue by chesterbr** [muan/github-gmail#70]
Hello!

Love your extension/add-on on GMail, thank you for the hard work!

I recently switched back from Chrome to Firefox, and realized it could not be installed there:

![2018-06-29_10-07-42](https://user-images.githubusercontent.com/236297/42096970-cb24756a-7b84-11e8-9454-567b61982583.png)

It seems Firefox Quantum (57+) only allows ["WebExtensions"](https://developer.mozilla.org/en-US/Add-ons/WebExtensions). I have no idea of the work involved into making this a WebExtension, but I'm opening the issue, just in case someone would like to try.

Thank you!

**Comment by muan** [comment]
I checked to see how hard it is and looks like it's not trivial: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on. 

I was so sure that the original firefox extension setup was a PR and not set up by me but git blame said I did it. 🙈 The code looks foreign to me now. 

Since I'm not a firefox user, I'd really appreciate if someone take this on! It's also pretty behind now: #36 #53.

**Comment by josephj11** [comment]
I am just starting to play around with Waterfox - a fork of Firefox before Quantum broke everything. Maybe your extension could be made to work there with less effort.
I just tried to install it there, but the install button was disabled for some reason.

I just installed the chrome version on Vivaldi. It's exactly what I was looking for! Thanks.

**Comment by Amazing-Amanda** [comment]
#

**Comment by Coding-Hen** [comment]
Has anyone tried porting the chrome extension across rather than changing the original Firefox? Firefox has made it much easier now to port from Chrome with many of the extensions apis similar.

**Comment by jorgemanzo** [comment]
The Chrome extension seems to be made with WebExtensions. I loaded the chrome version of the plugin into firefox 69.0.2, and heres whats working and what is not:
- The list view shortcut looks like its working. Clicking on it takes me to the issue.
<img width="875" alt="image" src="https://user-images.githubusercontent.com/26660036/66264559-71c34000-e7bc-11e9-974d-9a5d86131b7d.png">

- Mail view shortcut and mute thread are missing
<img width="945" alt="image" src="https://user-images.githubusercontent.com/26660036/66264571-a6cf9280-e7bc-11e9-87a7-588ab8b6cbe5.png">

Loading it into firefox gave the following warning:
```
Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.
```

I could give porting this over to firefox a shot!

**Comment by jorgemanzo** [comment]
Heres what I got so far from porting over the chrome version of the extension: https://github.com/jorgemanzo/github-gmail/commit/51300a6e5393215298c8c03bb0661080e7af98ef

The keyboard shortcuts dont work yet (ctrl + enter works). Everything else seems to be working!

**Comment by muan** [comment]
With 5bce1c90d80a6cac2312dc4411a0d5f3afde46e4 this should work now.

I've submit the updated version to Firefox Add-ons, we'll see how it goes. In the mean time, loading the `/firefox` folder from `about:debugging#/runtime/this-firefox` should work.

Shortcut can be managed here in Extensions -> Gear icon -> Manage Extension Shortcuts.

![image](https://user-images.githubusercontent.com/1153134/67645853-76819c80-f901-11e9-87da-aa5ab977e0c1.png)

![image](https://user-images.githubusercontent.com/1153134/67645870-8dc08a00-f901-11e9-9df0-9fa6ea47fb7d.png)

**Comment by muan** [comment]
Also thanks y’all for the discussion. Turns out it was indeed very easy porting it from the Chrome version which is already a webextension. I finally took this up because I’m trying to switch to Firefox. :) Most changes were deprecated methods. Switching to the standardized commands saved a ton of code. 👍

**Comment by muan** [comment]
It's approved! https://addons.mozilla.org/en-US/firefox/addon/github-for-gmail/
