### ISSUE TITLE
Visit Github thread button not showing

### ISSUE THREAD

**Issue by orschiro** [muan/github-gmail#74]
Dear @muan,

Could you please check if the button is still showing for you on the new Gmail interface?

For me it's not for some reasons. 😩

Thank you!

![image](https://user-images.githubusercontent.com/170947/53159167-99ff8500-35c5-11e9-9e96-70bdc42db986.png)

**Comment by muan** [comment]
Oh noes. I have not gotten the new UI. Is there a way to opt in?

**Comment by orschiro** [comment]
Hm strange. By now it should have reached everyone. 

Do you see a settings (gear) icon somewhere?

What happens if you click on it?

Do you have an option to switch to the new design?

**Comment by muan** [comment]
Nothing:

<img width="183" alt="image" src="https://user-images.githubusercontent.com/1153134/53275377-e2ec3200-36c8-11e9-8fa6-823456554720.png">

This was the recent new UI (and what I have): https://blog.google/products/gmail/stay-composed-heres-quick-rundown-new-gmail/ Was there another big update? 🤔

**Comment by orschiro** [comment]
Hmm, and for you it's showing the button? Can you show me a screenshot?

![image](https://user-images.githubusercontent.com/170947/53285287-2beec580-375f-11e9-95b3-dfd2fb5fcf11.png)

**Comment by muan** [comment]
Sure:

![](https://user-images.githubusercontent.com/1153134/53301451-18a42e80-3821-11e9-9363-e1b1e8b2f195.png)

Have you tried it without other gmail extensions?

**Comment by orschiro** [comment]
Not yet. Let me try!

Thanks for all your help thus far. 👍😄

-
