### ISSUE TITLE
Adding support for GitLab

### ISSUE THREAD

**Issue by infokiller** [muan/github-gmail#75]
Thanks for this project!

I'd like to add support for Gitlab as well.
Is this something you are open to adding and/or merging a PR?

Thanks!

**Comment by muan** [comment]
The codebase is quite dated and is due for a big refactor. I'd rather not widen the scope of this project for things I won't use/maintain. Feel free to fork it and publish your own version.

**Comment by infokiller** [comment]
Thanks for the response @muan 
So do you plan on doing a big refactoring "soon"? (no promises :)
I'm asking because if I'll decide to fork, it may make more sense to wait till it's done to be able to merge stuff more easily.

**Comment by muan** [comment]
I really don't know, so.. I guess that means, not soon. FWIW I'm referring to the Gmail DOM parsing part of the code, which I think could be abstracted out with https://github.com/kartiktalwar/gmail.js or similar libraries. But I've yet researched much into it.
