### ISSUE TITLE
Extension stopped adding View Issue on GitHub tooltip on individual email list entries

### ISSUE THREAD

**Issue by josephj11** [muan/github-gmail#78]
Now, I have to open the email in Gmail t get a link to the issue. This is still way better than nothing, but it adds an extra step.

I am using Vivaldi 3.5 (based on chromium) on kubuntu 18.04.

**Comment by xh3b4sd** [comment]
The extension stopped working for me like a week ago I guess. Usually I used the buttons in the mail, but now they are greyed out. /cc @muan 

<img width="353" alt="Screenshot 2021-05-15 at 13 51 43" src="https://user-images.githubusercontent.com/552769/118359637-b0b69b80-b584-11eb-8a08-b91e7ddea19a.png">

**Comment by muan** [comment]
@josephj11  That feature is dependent on the Gmail feature "go to action" 

![image](https://user-images.githubusercontent.com/1153134/120272860-4e79cc80-c2e0-11eb-8ad0-690aba6924c0.png)

If that button isn't present then there's no way for the extension to read the URL. Looks like GitHub or Gmail no longer does this. At least judging from the notification emails that I have in my inbox currently.

---

@xh3b4sd Should be fixed shortly. (once the extension update goes through)

**Comment by wagnerand** [comment]
@muan Thank you for fixing this. Would you mind submitting a new version to addons.mozilla.org as well?

**Comment by muan** [comment]
@wagnerand Done. Thanks for reminding me.

**Comment by xh3b4sd** [comment]
Works for me again. Thank you for your responsiveness. Appreciate the work a lot. ❤️ 

<img width="220" alt="Screenshot 2021-06-01 at 14 52 38" src="https://user-images.githubusercontent.com/552769/120326448-04491900-c2e9-11eb-9db9-c197d18492c8.png">
